### ISSUE TITLE
Error running CAPA(1.6.0) as library using vivisect backend

### ISSUE THREAD

**Issue by r0ny123** [fireeye/capa#459] opened 2021-03-09 12:40 UTC
### Description

The latest CAPA (1.6.0) failed to extract results from a pe file while using vivisect backend.

### Steps to Reproduce

1. `pip install flare-capa`
2. run `capa -r path/to/rules -b vivisect "tests/data/Practical Malware Analysis Lab 01-01.dll_"`
3. Get the following error :
```
loading : 100%|██████████████████████████████████████████████████████████████| 469/469 [00:04<00:00, 99.90     rules/s]
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\Scripts\capa.exe\__main__.py", line 7, in <module>
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\site-packages\capa\main.py", line 707, in main
    extractor = get_extractor(args.sample, args.format, backend, disable_progress=args.quiet)
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\site-packages\capa\main.py", line 346, in get_extractor
    return get_extractor_py3(path, format, backend, disable_progress=disable_progress)
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\site-packages\capa\main.py", line 329, in get_extractor_py3
    vw = get_workspace(path, format, should_save=False)
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\site-packages\capa\main.py", line 278, in get_workspace
    vw = viv_utils.getWorkspace(path, should_save=should_save)
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\site-packages\viv_utils\__init__.py", line 86, in getWorkspace
    vw.loadFromFile(fp)
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\site-packages\vivisect\__init__.py", line 2648, in loadFromFile
    fname = mod.parseFile(self, filename, baseaddr=baseaddr)
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\site-packages\vivisect\parsers\pe.py", line 36, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename, baseaddr=baseaddr)
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\site-packages\vivisect\parsers\pe.py", line 455, in loadPeIntoWorkspace
    s.parse()
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\site-packages\vtrace\platforms\win32.py", line 2154, in parse
    self.symInit()
  File "C:\Users\Rony\AppData\Roaming\Python\Python38\site-packages\vtrace\platforms\win32.py", line 2105, in symInit
    x = dbghelp.SymLoadModule64(self.phandle,
ctypes.ArgumentError: argument 3: <class 'TypeError'>: wrong type
```
  

### Expected behavior:

CAPA should extract the information as expected.

### Actual behavior:

See 3.

### Versions:
`CAPA 1.6.0`
`windows 10`
`python 3.8`

### Additional Information
I also setup an workflow to re-verify the issue, the CI failed for `V1.6.0` but It's all good in `V1.5.1`.
This is the workflow file I have used to check:
```
name: capa 1.6.0

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with: 
         python-version: 3.8
      - name: Install capa from pypi
        run: pip install flare-capa
      - name: Checkout capa
        uses: actions/checkout@v2
        with:
         repository: fireeye/capa
         submodules: true
      - name: Does it run?
        run: capa -r rules -b vivisect "tests/data/Practical Malware Analysis Lab 01-01.dll_"
```

**Comment by mr-tz** [comment] 2021-03-09 13:34
In my Python 2 installs the dbghelp DLLs appear to be missing? However, they are present in Python 3.

```
$ ls -R /c/Python27/Lib/site-packages/vtrace/platforms/windll/
/c/Python27/Lib/site-packages/vtrace/platforms/windll/:
__init__.py*  __init__.pyc*  amd64/  i386/

/c/Python27/Lib/site-packages/vtrace/platforms/windll/amd64:
__init__.py*  __init__.pyc*

/c/Python27/Lib/site-packages/vtrace/platforms/windll/i386:
__init__.py*  __init__.pyc*

```

**Comment by r0ny123** [comment] 2021-03-09 14:07
> 
> 
> Ugh, this is fixed in https://github.com/vivisect/vivisect/pull/372/files#diff-12729e49dd95391f9160e3f0f7422924083f12383b3afe94a5e9ee48d87fee34R2105 which was added just after the vivisect 1.0.0 release. In the meantime you should be able to run with vivisect installed from master.
> 
> This happens in `vtrace`/`dbghelp` which I think we don't need and should disable, if possible?

Thanks for the info. Will check soon!

**Comment by r0ny123** [comment] 2021-03-09 14:16
Should we make viv guys to release vivisect 1.0.1 with vivisect/vivisect#372 and also release a capa version 1.6.1? What do you think :) ?

**Comment by Ana06** [comment] 2021-03-09 14:27
I have just asked in vivisect. We should release capa 1.6.1 once vivisect 1.0.1 has been released. Thanks for the report @r0ny123!

**Comment by williballenthin** [comment] 2021-04-06 03:24
#512

**Comment by Ana06** [comment] 2021-04-06 08:19
Addressed in #512

**Closed by Ana06** 2021-04-06 08:19 UTC
Labels: blocked-on-viv, bug

**Comment by r0ny123** [comment] 2021-04-06 09:35
I don't think this issue addressed in #512 as it depends on #470.
see https://github.com/fireeye/capa/pull/470/checks?check_run_id=2276807051

**Comment by Ana06** [comment] 2021-04-06 10:46
@r0ny123 

> I don't think this issue addressed in #512 as it depends on #470.
see #470 (checks)

#512 updates the vivisect version to the one which should include the fix for this. #470 tests that it works. As you have pointed out, the checks fail, but this is caused by the smda backend (which was also failing before), not by vivisect. All the vivisect tests are working in Windows with Python 3.9 since #512 was merged.
 
![Screenshot 2021-04-06 at 12 41 02](https://user-images.githubusercontent.com/16052290/113699030-5b5db380-96d5-11eb-8baf-0443839097ae.png)

So I think this issue is fixed. Please feel free to try if the problem is solved for you using master code.

**Comment by r0ny123** [comment] 2021-04-07 14:49
Ugh, I overlooked that, thanks @Ana06!

**Comment by Ana06** [comment] 2021-04-07 16:18
@r0ny123 capa v1.6.1 (including this fix) is released

**Comment by r0ny123** [comment] 2021-04-07 17:19
@Ana06 Just ran capa against a file. Worked perfectly fine!
