### ISSUE TITLE
missing author on multiple authors

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#554] opened 2021-05-10 16:00 UTC
see Changelog line
`host-interaction/network/connectivity/check-internet-connectivity-via-wininet author:`

stems from rule with
```
author:
  - A
  - B
```

**Comment by Ana06** [comment] 2021-05-11 10:40
duplicate of https://github.com/fireeye/capa/issues/555 (sorry 🙈 )

**Closed by Ana06** 2021-05-11 10:40 UTC
Labels: CI
